[tool.sire.build]
cpp_build_type = "release"
py_install_type = "release"
cpp_base_path = "D:\\code\\sire"
aris_path = "D:\\code\\sire\\third_party\\install\\aris"
fcl_path = "D:\\code\\sire\\third_party\\install\\hpp-fcl"
uuid_path = "D:\\code\\sire\\third_party\\install\\stduuid"
toolchain_path = "D:/vcpkg/scripts/buildsystems/vcpkg.cmake"
build_test = false
build_demo = false
build_python = true
sire_enable_tracy = false
sire_clarabel_force_source_build = false
cmake_only = false
rm_cmake_cache = false
rerun_config = false
